import "./globals.css"
import { Inter } from "next/font/google"
import Providers from "./Providers"

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js"
}

export const InterFont = Inter({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"]
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${InterFont.className} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
