import "./globals.css"
import Providers from "./Providers"

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js"
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
